// app/page.tsx

import Head from 'next/head';
import styles from './Components/Home.module.css';
import Navbar from './Components/Navbar';
import Gallery from './Components/Gallery';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Next.js Home Page
        </h1>
        <p className={styles.description}>
          This is a simple, clean, and neutral home page design.
        </p>
        <Gallery />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/vercel.svg" alt="Vercel Logo" className={styles.logo} />
        </a>
      </footer>
    </div>
  );
}
